# ============================================================================
# SCHEMAS/AUTOFIX.PY — AI Auto-Fix Request/Response Models
# ============================================================================
# Data shapes for the AI code fix generation endpoints:
#   - AutoFixRequest:         Fix issues from a specific commit analysis
#   - AutoFixCustomRequest:   Fix a user-provided code snippet + issue
#   - CodeFix:                A single code fix (before/after/explanation)
#   - AutoFixResponse:        Full response with all generated fixes
#   - AutoFixCustomResponse:  Response for ad-hoc code fix requests
#
# Key design: Fixes are ON-DEMAND only — the user must explicitly request
# them after reviewing their analysis report.
# ============================================================================

from pydantic import BaseModel


class AutoFixRequest(BaseModel):
    """Request to generate fixes for issues found in a commit analysis.

    The user provides the repository + commit, and optionally which
    specific issues they want fixed (by index). If issue_indices is
    empty, fixes are generated for ALL fixable issues.
    """
    repository_id: int
    commit_sha: str
    issue_indices: list[int] = []  # Empty = fix all fixable issues


class AutoFixCustomRequest(BaseModel):
    """Request to fix a specific code snippet with a described issue.

    The user pastes their code and describes what's wrong — the AI
    generates a corrected version. No GitHub or analysis required.
    """
    code_snippet: str
    language: str = "python"
    issue_description: str
    file_name: str = "untitled"


class CodeFix(BaseModel):
    """A single code fix generated by the AI.

    Shows the original code, the fixed version, what changed,
    and how confident the AI is in the fix.
    """
    issue_title: str = ""
    issue_type: str = ""  # security | performance | architecture | quality
    severity: str = "medium"  # low | medium | high
    file_name: str = ""
    original_code: str = ""
    fixed_code: str = ""
    explanation: str = ""
    confidence: str = "medium"  # low | medium | high


class AutoFixResponse(BaseModel):
    """Full auto-fix response containing all generated code fixes.

    Returned after the AI processes the analysis and generates
    corrected code for each requested issue.
    """
    commit_hash: str = ""
    total_issues_found: int = 0
    total_fixes_generated: int = 0
    fixes: list[CodeFix] = []
    summary: str = ""


class AutoFixCustomResponse(BaseModel):
    """Response for a custom (ad-hoc) code fix request.

    Returns the fixed code along with explanation and confidence.
    """
    file_name: str = ""
    language: str = ""
    original_code: str = ""
    fixed_code: str = ""
    explanation: str = ""
    confidence: str = "medium"
    additional_suggestions: list[str] = []
